# Generated by Django 4.2.11 on 2024-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
