# Generated by Django 4.2.11 on 2024-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_age_remove_blog_writter_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
